'''
now = ['Ismail','Sadia','Mazumder','Ali','Hamja','Ismail']
now.remove('Ismail')
#print(len(now))
now.pop(0)
print(now)
'''
import random
import pyautogui
import time
#while True:
print("Wait 5 second.")
time.sleep(1)
'''
#pyautogui.press('ctrl','shift','S')
pyautogui.hotkey('ctrl', 'shift', 's')
pyautogui.press('s')
'''
pyautogui.press('I')
time.sleep(1)
pyautogui.press('s')
time.sleep(1)
pyautogui.press('m')
time.sleep(1)
pyautogui.press('a')
time.sleep(1)
pyautogui.press('i')
time.sleep(1)
pyautogui.press('l')
time.sleep(1)
pyautogui.press('space')
time.sleep(1)
pyautogui.press('M')
time.sleep(1)
pyautogui.press('a')
time.sleep(1)
pyautogui.press('z')
time.sleep(1)
pyautogui.press('u')
time.sleep(1)
pyautogui.press('m')
time.sleep(1)
pyautogui.press('d')
time.sleep(1)
pyautogui.press('e')
time.sleep(1)
pyautogui.press('r')
time.sleep(1)
#time.sleep(1)
pyautogui.press('space')
time.sleep(1)
pyautogui.press('i')
pyautogui.press('s')
pyautogui.press('space')
pyautogui.press('m')
pyautogui.press('y')
pyautogui.press('space')
time.sleep(1)
pyautogui.press('n')
pyautogui.press('a')
pyautogui.press('m')
pyautogui.press('e')
pyautogui.press('.')

#save
#pyautogui.press('ctrl','s')
pyautogui.hotkey('ctrl','shift','s')